### ISSUE TITLE
Touch Current Index

### ISSUE THREAD

**Issue by pothirajp** [uias/Pageboy#101]
@msaps 
Hi...,
i want to track the user current touch index, its possible ?
if there means let me know

**Comment by cody1024d** [comment]
Interested in knowing if this is possible as well.

**Comment by msaps** [comment]
@pothirajp what exactly do you mean by the current touch index? Not entirely sure of the context 😄

**Comment by cody1024d** [comment]
I think what he means, at least in my case, what I would need it to do, is know when the currently selected tab is pressed again.
