### ISSUE TITLE
This issue was posted by mistake

### ISSUE THREAD

**Issue by thechaudharysab** [uias/Pageboy#104]
This question was posted by mistake.

**Comment by msaps** [comment]
Hi,

Not quite sure how this issue is related to Pageboy, how exactly are you using Pageboy with XLPagerTabStrip? From first look it looks as though its a layout issue with the tab bar view?

Cheers 🙂

**Comment by thechaudharysab** [comment]
Ooo.. my bad I was supposed to post this issue on XLPagerTabStrip. Sorry I'm new to posting issues on github so somehow I posted it here as I was exploring other options. Kindly delete this question as it would be relevant to anyone.

**Comment by msaps** [comment]
No worries! 🙂
