### ISSUE TITLE
Scrolling with the bouncing off causes the current page to be incorrectly offset.

### ISSUE THREAD

**Issue by bobek-balinek** [uias/Pageboy#108]
When I've set the `bounce` to `false` and flicked the pages with a bit more impact I noticed it incorrectly offsets the current page. Below is a short gif with the issue (Pink rectangles are the bounds of the view controllers to help visualise the issue):

![c](https://user-images.githubusercontent.com/913452/31542333-7add12ca-b009-11e7-93ab-0ce6fcc89b17.gif)

**Comment by msaps** [comment]
Hi, 

Yeah I've seen this before. Unfortunately the method to disable bouncing when using a `UIPageViewController` isn't pretty at all and doesn't quite work right. I'll have a look at seeing whether I can improve it 👍
