### ISSUE TITLE
Page Control UI

### ISSUE THREAD

**Issue by alexjessecole** [uias/Pageboy#116]
Is there a way to display the native Page Control UI element using Pageboy? Any help would be greatly appreciated.

**Comment by msaps** [comment]
@alexjessecole I'll try and get this exposed in the API in some way in the next update 👍

**Comment by msaps** [comment]
This is now available via `showsPageControl` as of [2.1.0](https://github.com/uias/Pageboy/releases/tag/2.1.0) 🎉

**Comment by dmitry-kovba** [comment]
I do not see it in the latest available version of `Pageboy`.
