### ISSUE TITLE
[Bug in 2.0.3] Setting data source in initializer breaks `updateViewControllers` 

### ISSUE THREAD

**Issue by Burgestrand** [uias/Pageboy#118]
It's just one of the ways of breaking the internals, however. The cause is a guard from within `updateViewControllers` that is never reset.

Whenever we call `updateViewControllers` we [first check if we're already in the process of updating, and if we are we bail out](https://github.com/uias/Pageboy/blob/ebc822bc83f576c43927d7325709b4dd1e5f2e47/Sources/Pageboy/PageboyViewController.swift#L408). If not, we continue.

First thing we do is [toggle the flag](https://github.com/uias/Pageboy/blob/ebc822bc83f576c43927d7325709b4dd1e5f2e47/Sources/Pageboy/PageboyViewController.swift#L412), so that we won't go in here again before we're complete.

We then perform our work, and when our `pageViewController` has finished setting the view controllers we [clear the flag](https://github.com/uias/Pageboy/blob/ebc822bc83f576c43927d7325709b4dd1e5f2e47/Sources/Pageboy/PageboyViewController.swift#L423) so that we may call `updateViewControllers` some time again in the future.

The problem lies in that `pageViewController` might be `nil`, and if it is then we'll _never_ call the completion block, and thus we'll never clear the `self.isUpdatingViewControllers` flag, and every invocation of this method in the future will exit early.

**Comment by msaps** [comment]
@Burgestrand thanks for this and all the detail.. 

I've now fixed the issue and released it as part of [2.0.4](https://github.com/uias/Pageboy/releases/tag/2.0.4) 👍

**Comment by Burgestrand** [comment]
Thank you!
