### ISSUE TITLE
Unable to change Child view controllers navigation title when view controller swapped.

### ISSUE THREAD

**Issue by vinodiOS** [uias/Pageboy#119]
I want to change title of child controllers when they scrolled or navigated using barItemButtons.

**Comment by msaps** [comment]
@vinodiOS you can do this pretty easily by utilising the `PageboyViewControllerDelegate`. When a page is scrolled to, you can use the `currentViewController` property to access the visible child view controller and update the parent navigation title.

Something like this:
```swift
func pageboyViewController(_ pageboyViewController: PageboyViewController,
                               didScrollToPageAt index: Int,
                               direction: PageboyViewController.NavigationDirection,
                               animated: Bool) {
     let childTitle = pageboyViewController.currentViewController?.title
     pageboyViewController.navigationItem.title = childTitle
}
```

**Comment by vinodiOS** [comment]
Thank you @msaps
