### ISSUE TITLE
Custom transition not working

### ISSUE THREAD

**Issue by rainypixels** [uias/Pageboy#125]
I'm not sure if I'm missing something, but I'm unable to get the custom transition to work.

I set it as follows:

```
required public init?(coder aDecoder: NSCoder) {
  super.init(coder: aDecoder)  
  self.transition = Transition(style: .fade, duration: 1.0  )
}
```
It seems to be set (I can print it to the console in `viewDidAppear`), but it is never applied.

**Comment by msaps** [comment]
@rainypixels I will check it out 👍

**Comment by rainypixels** [comment]
@msaps My bad! I just wired up some buttons to `scrollToPage`, and sure enough, the custom transitions are working. I was expecting them to work when you swipe to page, but understandably, that's not custom transitions would (or should) do in this case. Apologies if you've already investigated or spent any time clarifying this bug. Everything is working as designed. 💯

**Comment by msaps** [comment]
@rainypixels ahh right! no worries 😄 

Might be interesting to see if I could achieve custom interactive transitions though...

**Comment by rainypixels** [comment]
Hey, I'm not going to argue with that. :) I'd definitely be able to use it. It's definitely technically possible; your custom transition architecture is elegant, and I could see it easily be extended to do that even on a page level (i.e. when say you go from page 0 to 1, it does a push, but 1 to 2 does does a moveIn = similar to SnapChat's gesture for navigating to their Discovery section, the right-most page).
