### ISSUE TITLE
Module compiled with Swift 4.0.1 cannot be imported in Swift 4.0.2

### ISSUE THREAD

**Issue by annjawn** [uias/Pageboy#127]
Getting this error on XCode 9.1 (Stable) and Swift 4.2.

`Module compiled with Swift 4.0.1 cannot be imported in Swift 4.0.2`

**Comment by msaps** [comment]
@annjawn what version of the Xcode build tools are you using? `xcodebuild -version`. The CL tools are probably using an older version of Xcode than you want to build with.
