### ISSUE TITLE
PageboyView not extending to Bottom of Screen on iPhone X

### ISSUE THREAD

**Issue by otymartin** [uias/Pageboy#128]
Hey @msaps 
This is a freak issue in that it just appeared out of nowhere but Im hoping you can give me hints.

So basically my ViewHierachy is like this
```
-> ParentViewController 
----> PageboyViewController (Child of Parent)
----------> LeftVC
----------> MainVC
```
It appears my PageboyVC's childControllers (LeftVC & MainVC) does not extend to the bottom of the screen on an iPhone X. Ive had instances where it was working fine but the issue recently reappeared without me able to retrace what exactly I could have done to cause it(up to now i can't pinpoint)

Any hints? I haven't been able to recreate it with your example project but will try it out tomorrow.

Thanks

**Comment by msaps** [comment]
@otymartin does the `PageboyViewController` view frame extend to the bottom of the screen? Should be pretty easy to see with the view debugging inspector, can then have a look whether this is something within Pageboy or not 👍

**Comment by otymartin** [comment]
@msaps it does extend to the bottom. Its the child views (datasource vc's) that dont. For whatever reason view debugger doesn't work for me. Dont know if its related to Xcode 9.2 or not.

**Comment by msaps** [comment]
@otymartin found the issue. It's occurring due to something that changed with `UIPageViewController` in iOS 11.2 - [iOS 11.2 Release Notes](https://developer.apple.com/library/content/releasenotes/General/RN-iOS-11.2/index.html). 

Going to raise a bug and see what I can find out 👍

**Comment by msaps** [comment]
If you're interested - the child view controllers of a `UIPageViewController` don't seem to extend the full height of the screen when you implement `presentationCount(for pageViewController: UIPageViewController) -> Int` even if the page indicator is not visible.

**Comment by otymartin** [comment]
@msaps never implemented `presentationCount` I will be tackling this issue this week so if i find a culprit with solution will definitely address it here.

**Comment by msaps** [comment]
@otymartin Pageboy implements it to provide support for `showsPageControl`. But the layout of the child view controllers is adjusted when it shouldn't be. I've raised a radar, and might disable the built in page control temporarily in a new version until this is fixed/clarified..

**Comment by msaps** [comment]
@otymartin I've temporarily removed the usage of `showsPageControl` so that the 11.2 problem is resolved until I hear anything from Apple. Using [2.2.0](https://github.com/uias/Pageboy/releases/tag/2.2.0) should fix the issue 👍

**Comment by otymartin** [comment]
@msaps beautiful, my eyes did not read this.
`@otymartin found the issue. It's occurring due to something that changed with UIPageViewController in iOS 11.2 - iOS 11.2 Release Notes`
Will check it out now :)

**Comment by otymartin** [comment]
@msaps Can confirm the problem is fixed. Yay! Thanks man 👊

**Comment by Graystripe17** [comment]
Using 2.2.0, it does not appear. I get the deprecated warning in XCode and the page controller doesn't work.
Using 2.5.0, it gives me the same message but this time an error.
Has the problem been solved?
@otymartin @msaps

**Comment by otymartin** [comment]
@Graystripe17 I no longer have this problem however will keep a lookout and reach back if I find anything.

**Comment by msaps** [comment]
@Graystripe17 @otymartin `showsPageControl` was marked as `unavailable` in Pageboy [2.4.0](https://github.com/uias/Pageboy/releases/tag/2.4.0) - the layout repercussions are pretty severe and I haven't heard anything back on the radar 😢

**Comment by sabiland** [comment]
Looks like showsPageControl is still unavailable in 2.6 ?

**Comment by dmitry-kovba** [comment]
How should we show the `UIPageControl` now?
