### ISSUE TITLE
Is it possible to add peeking to PageBoy?

### ISSUE THREAD

**Issue by jordanpwood** [uias/Pageboy#137]
Pageboy and Tabman look great, and I would love to use them in my project!  However, one of the requirements is that I be able to "zoom out" and show the edges of adjacent pages.  I'm not sure this is possible with a UIPageViewController.  Do you know if it's even possible for Pageboy to implement this feature?  If not, is it possible to decouple Tabman and Pageboy, putting in something (UIScrollView?) that can conform to a Pageboy protocol? 

Thanks for your time, and thanks for adding to the open source community!

**Comment by msaps** [comment]
@jordanpwood thank you very much for the kind words! 😄 

I'm not sure whether its possible either, will have to do a bit of investigation but I'd imagine also that `UIPageViewController` might not play too nicely with that sort of feature. 

I also love the idea of decoupling stuff a bit more, so will see if I can improve this in the near future 👍 

I'll update with what I can find...
