### ISSUE TITLE
NavigationBar Item Transition on Swipe

### ISSUE THREAD

**Issue by otymartin** [uias/Pageboy#138]
@msaps 
Is it possible to have navigation bar items and titles transition in the manner shown below (Either with Pageboy or Tabman)? It makes for a very simple & intuitive navigation scheme in my opinion.

![nav](https://user-images.githubusercontent.com/2222881/35452888-2c1d7cda-0296-11e8-9c59-f6c60c0a91d8.gif)

**Comment by msaps** [comment]
@otymartin sorry I didn't reply on Twitter, been super busy lately! 

This should actually be possible (maybe?) with Tabman currently. I'll check it out and see if I can get the appearance config you'll need to make this work. If not I'll raise a relevant issue in Tabman for what we need, but it should be possible! 🤞

**Comment by otymartin** [comment]
@msaps Beautiful, man much appreciated. Looking forward to it.

**Comment by otymartin** [comment]
@msaps 
Hey im looking to hack together a premature implementation of this to push to an existing app fast on Appstore while I await your official implementation, I was wondering if you can give me some logical guidance for how to achieve the appearance config needed for this behaviour. 

So far my only ideas are to use a custom TabmanBar, center distributed and figure out the right amount of spacing between each barItem.

Then use this delegate method to update the position of each element relative to the swipe direction and destination page. Any other hints?
```swift 
override func update(forPosition position: CGFloat,
                direction: PageboyViewController.NavigationDirection,
                indexRange: Range<Int>,
                bounds: CGRect) { }
```

**Comment by msaps** [comment]
@otymartin apologies, having looked at the effect a bit more properly I don't think this *exact* style can be achieved by vanilla Tabman currently. 👎 

But yeah you are on the right track with a custom bar! The custom support available in 1.X is pretty rudimentary, as it wasn't a big priority for getting Tabman out there! Hopefully going to improve this with 2.0... 

But anyway.. 

I think you're pretty spot on with how to achieve it. The tricky part will be figuring out the correct X spacing between the items. Tabman provides no interference or help with creating your bar, just gives the raw values for updating and lifecycle functions currently. So you are free to use whatever view components for the bar items and manipulate them however you want! 

Appreciate this isn't the most helpful for extending easily, but as I said, v1.0 😄

**Comment by otymartin** [comment]
@msaps Ok great, let me give this a try. Thanks :)

**Comment by msaps** [comment]
@otymartin going to close this as it's more of a Tabman issue, but please feel free to raise something in there with how you get on / if you need any help 🙂
