### ISSUE TITLE
Maybe there is a bug with UIPageViewController in iPhone X

### ISSUE THREAD

**Issue by beimen** [uias/Pageboy#148]
I have the same issue while I used Pageboy:

https://stackoverflow.com/questions/47883195/uipageviewcontroller-in-combination-with-safe-area

I used the latest version(2.4.0). I have scanned the existing issues, it seems there is no issue about it. So I create this issue.

**Comment by otymartin** [comment]
@beimen check if its related to #128

**Comment by beimen** [comment]
I had read it. But I think that’s an another bug.

**Comment by msaps** [comment]
@beimen @otymartin will take a look and see if I can reproduce. We're not doing anything funky with safe areas in Pageboy so it might be a `UIPageViewController` issue
