### ISSUE TITLE
Parent is not loading next view controller as like UiPageViewController

### ISSUE THREAD

**Issue by aaasifrz9** [uias/Pageboy#151]
Hi,

Parent view controller is not loading child next view controller as like UiPageViewController.

Can we load next/previous page when current page loads as like UIPagerViewController using PageBoy framework? If possible, please suggest how can we implement?

Thanks,
Asif

**Comment by msaps** [comment]
@aaasifrz9 Pageboy uses `UIPageViewController` underneath for all page view controller logic. `PageboyViewController` is pretty much a wrapper around it that just provides a nicer data source and delegation improvements. 

So the `viewController(for: at:)` data source function is called whenever the internal `UIPageViewController` asks for a view controller in `pageViewController(viewControllerBefore:)` or `pageViewController(viewControllerAfter:)`. See [PageboyViewController+Management](https://github.com/uias/Pageboy/blob/6077a2919747436ff45861d1ae2d825938b0f16f/Sources/Pageboy/Extensions/PageboyViewController%2BManagement.swift#L235).

**Comment by msaps** [comment]
Closing, please continue discussion in #144. Duplicate issues for comments aren't required please 👍
