### ISSUE TITLE
How can I insert a new child controller and move to the inserted controller without reloadPages?

### ISSUE THREAD

**Issue by aaasifrz9** [uias/Pageboy#152]
Hi @msaps ,

I am stuck at a scenario.

Suppose currently I have total 6 child controllers loaded and at position (index 3: Position 4). Now I inserted a new child controller at last index (index 6: Position 7).
Now I moved to last index using
First: `self.reloadPages()` then `self.scrollToPage( .last, animated: false)`

But when I reloadPages then target moves to first index (index 0: Position 1) and then moves to last index. Means I am able to see that user moves from index 3 to 0 then index last.

I want without reloadPages moves from index 3 to last index. I don't want to move to index 0 and then to last index. Is it possible? Please help.

**Query 1:** How can I insert a new child controller and move to the inserted child controller without reloadPages?
**Query 2:** How can I delete a new child controller and move to adjacent pre/next child controller without reloadPages?

I am not able to do it directly. Please help. I have spent to much time to solve but no success.
Thanks in advance.

**Comment by msaps** [comment]
@aaasifrz9 as mentioned in #135 this is a new feature that will be added soon. Going to close and try to centralise in #155 👍
