### ISSUE TITLE
Transition wont work

### ISSUE THREAD

**Issue by EnochCube** [uias/Pageboy#154]
Hi,

when i change transition style to push or another, just transition scroll style that work, no change!

..
pageboyVC.transition = Transition(style: .push, duration: 2)
present(pageboyVC, animated: true, completion: nil)

Thanks

**Comment by EnochCube** [comment]
sry its working, but not by swipe, !?

**Comment by msaps** [comment]
@EnochCube yeah sorry the custom transitions only currently work for animated transitions, no the interactive scrolling.
