### ISSUE TITLE
Second swipe when the first is not finished

### ISSUE THREAD

**Issue by jbdujardin** [uias/Pageboy#157]
Hi!

Sorry for my bad english...
I have found a bug when I do a second swipe and the first is not finished : 
* The background color is blue and not orange
* The Current Position and Current Page are 0.0, not 1.0
* "Previous" button is disabled
* Text is good (Page 2) for the first test but nothing appear for the second test

The screen record :

![ezgif com-optimize](https://user-images.githubusercontent.com/293027/38376144-3c64b408-38f8-11e8-9f90-f0b9e2575d35.gif)

Thanks for your help

**Comment by msaps** [comment]
@jbdujardin any hints on how to reproduce this? I'm really struggling to find it

**Comment by jbdujardin** [comment]
@msaps With the exemple, you start a incomplete light swipe to the second page and before the swipe returns to its original position you do a full swipe to the second page.
It's not easy to reproduce but in iPad application it's really binding.

**Comment by jbdujardin** [comment]
@msaps Perfect! It works perfectly!
Thank you for your good work and your nice library :)

**Comment by msaps** [comment]
@jbdujardin great! Thank you!! 😄

**Comment by aaasifrz9** [comment]
Hi @msaps , 

How can I use this? I tried `Pageboy.xcodeproj` in my project. It gives me `No such module 'Pageboy'` when I am importing `import Pageboy`. How can I resolve it?

I also tried pod with 2.5 version, not working.

**Comment by aaasifrz9** [comment]
Hi @msaps ,

I tried 2.5.0 in my project. I have added 6 childs. 
Steps:-
1- On app starts app loads first child.
2- Then I swipe to move 2nd child and it moves.
3- Then I tried to swipe fast (swipe swipe swipe ...) then it crashes with black screen. I got jump issue again. See the log last 6 lines.

I have attached crash log with screenshots. Please review and let us know. How to fix it.
[Error log.zip](https://github.com/uias/Pageboy/files/1886067/Error.log.zip)

Thanks
Asif

**Comment by Dfmarulanda** [comment]
![ezgif-1-5d9192d2b678](https://user-images.githubusercontent.com/2466498/58516569-f5fe1a80-816d-11e9-850f-e0779fa46244.gif)
