### ISSUE TITLE
index is negative when infinite scroll is enabled and didScrollToPageAt function is executed

### ISSUE THREAD

**Issue by ejosephwilson** [uias/Pageboy#159]
The index value for the didScrollToPageAt function is negative while infinite scroll is enabled and a user scrolls backwards from index position 0. For comparison, when executing the willScrollToPageAt function the index value is correct as it reports the final index position in the viewControllers array.

I believe this to be a bug. Please let me know if you need any further information.

Thanks!

**Comment by msaps** [comment]
@ejosephwilson will check it out and get it fixed ASAP! 😄

**Comment by msaps** [comment]
@ejosephwilson just released [2.5.1](https://github.com/uias/Pageboy/releases/tag/2.5.1) which should resolve this issue 😄

**Comment by ejosephwilson** [comment]
Great thank you!
