### ISSUE TITLE
Index parameter in viewController(for:at:) data source method changes immediately upon swipe

### ISSUE THREAD

**Issue by eirikvaa** [uias/Pageboy#169]
Hi,

I'm not sure if this is an issue, but if I print out the value of the `index` parameter in the `viewController(for:at:)` data source method, then it's (for example) 0 before I swipe and 1 immediately after I start swiping. I checked out the example project in this repository, and that project just updates the user interface when the user has performed a swipe, so you don't experience that particular "problem" there. I want the same behavior as you get with a regular `UIPageViewController` – you can see the contents of the other pages as you swipe to them, and the `index` is reliably assigned to a view controller. I know about `currentIndex` and `currentPosition`, but those won't help me as I don't want to refresh the list after I have finished swiping to it. Is this supported? I display a list of audio recordings in each view, and when I start swiping the list content changes because suddenly that page has the next `index`, and not the one it's supposed to have, even though the swipe motion isn't complete.

Thanks for any help!

**Comment by msaps** [comment]
@eirikvaa hey!

`viewController(for:at:)` isn't really meant to be used as a reliable way to detect the index of a page. The function is called sporadically whenever the internal `UIPageViewController` needs a new view controller to display.

I'm not really sure how your data is loaded and the relationship it has to the view controller index. Are you initialising view controllers within your `viewController(for:at:)` function?

**Comment by eirikvaa** [comment]
I create a list of view controllers in `viewDidLoad`. I have a `Project` object that contains multiple `Section` objects, and I fetch all `Section` objects in `viewDidLoad` and create the view controllers. In `viewController(for:at)` I return the correct view controller, but because the `index` changes sporadically I can't seem to return the correct view controller.
