### ISSUE TITLE
Swift 4.2 Support?

### ISSUE THREAD

**Issue by ThoseGuysInTown** [uias/Pageboy#174]
I seem to be getting errors like this:

`Type 'CATransitionSubtype' (aka 'NSString') has no member 'fromLeft'`

in TransitionOperation+Action
as well as other places. 

Am I doing something wrong?

**Comment by msaps** [comment]
@ThoseGuysInTown just released [2.6.0](https://github.com/uias/Pageboy/releases/tag/2.6.0) which has Swift 4.2 support 🎉
