### ISSUE TITLE
Invalid page when popping from navigation controller

### ISSUE THREAD

**Issue by Vapor-ios** [uias/Pageboy#180]
Hi,

I have a hierarchy like this:
UINavigationController > UIViewController with Pageboy as a child VC
Pageboy contains 3 pages

Reproduce steps:
1. Move pageboy with gesture, then cancel scrolling and stay on the page it was before scrolling started

2. Push a VC on the navigation controller and pop/start interactive gesture from it

Expected results:
I’d see Pageboy on the page I saw it before pushing

Actual results:
Pageboy is moved to a page of the direction Towards which I was scrolling to, even though I cancelled it

This occurs in 2.6 and 2.6.1 (even though I saw a similar issue #750, this fix didnt help)

However, this is working properly on the 3.0 branch.

Please take a look if you can - if you have any questions, don’t hesitate to ask.

Thanks in advance and I must say I really love this Pageboy pod :) Great work!

**Comment by msaps** [comment]
[Pageboy 3](https://github.com/uias/Pageboy/releases/tag/3.0.0) is now available, so will close this 🎉
