### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by yubaokang** [uias/Pageboy#182]
￼
![aaaaaaaaaaaaaaaa](https://user-images.githubusercontent.com/7115700/46943787-fea05580-d0a2-11e8-9e09-c1b520857ef5.jpeg)

**Comment by msaps** [comment]
[Pageboy 3](https://github.com/uias/Pageboy/releases/tag/3.0.0) now supports building in both Swift 4 & Swift 4.2 🎉
