### ISSUE TITLE
pod 'Pageboy', '~> 3.0'

### ISSUE THREAD

**Issue by SamboVisal** [uias/Pageboy#186]
I unable to install this pod version.
I have used `pod repo update` and then `pod install` then still not work

**Comment by msaps** [comment]
@SamboVisal what error is CocoaPods giving you?

**Comment by SamboVisal** [comment]
It states that

`CocoaPods could not find compatible versions for pod "Pageboy":
  In Podfile:
    Pageboy (~> 3.0)`

`None of your spec sources contain a spec satisfying the dependency: `Pageboy (~> 3.0)`.`

What happen??

**Comment by msaps** [comment]
@SamboVisal must be something to do with your pods installation, seems to work fine. Do you maybe have issues with your specs sources?
