### ISSUE TITLE
[3.0.0] Fatal error: Attempted to read an unowned reference but the object was already deallocated

### ISSUE THREAD

**Issue by RamblinWreck77** [uias/Pageboy#187]
Hello! I've been tracking a rare but annoying crash in production and think I have it figured out.

The gist of it is our app purges the view hierarchy (by switching the key window to a new blank view controller) when backgrounded in order to absolutely minimize memory usage before we get suspended. This is important for a core feature in our app to function well as it effects our background wake up from suspend frequency. 

The issue seems to be in PageboyViewController+Management.swift line 101. It looks like what can happen is:

1) App is backgrounded while animation is playing
2) View hierarchy is destroyed
3) updateBlock is called, and the unowned self doesn't exist because of above
4) app blows up

Switching "unowned self" to "weak self" fixes this according to our testing. 

Thanks for a great library!

**Comment by msaps** [comment]
@RamblinWreck77 should hopefully be fixed in [3.0.1](https://github.com/uias/Pageboy/releases/tag/3.0.1) 😄

**Comment by RamblinWreck77** [comment]
@msaps  thanks for the quick response/fix!
