### ISSUE TITLE
Pages not added

### ISSUE THREAD

**Issue by Mattijah** [uias/Pageboy#209]
Starting with an empty PageViewController and calling `insertPage` to insert a new page (or any subsequent page) seems to have no effect. The one need to first call `reloadData` for the first page and only then `insertPage` starts working...

*`currentIndex` is also not set

**Comment by msaps** [comment]
@Mattijah fixed in [3.2.2](https://github.com/uias/Pageboy/releases/tag/3.2.2) 🎉
