### ISSUE TITLE
Unable to run cloned project.

### ISSUE THREAD

**Issue by Sahilberi** [uias/Pageboy#224]
Hi, I am unable to build the cloned project as it is showing unable to import BLTNBoard framework.

**Comment by mseanbonner** [comment]
Hi @Sahilberi, I ran into same issue. Check out steps [here](https://github.com/uias/Tabman/blob/master/CONTRIBUTING.md#setting-up-the-project-for-development).  Pageboy and Tabman have similar Carthage dependency framework/structure, so I followed those steps (primarily `carthage bootstrap --platform ios` ) and got it building!
