### ISSUE TITLE
Have page transition above Next or Previous Page (Z-Index)

### ISSUE THREAD

**Issue by otymartin** [uias/Pageboy#24]
@msaps 
This is another question/feature request.
I implemented `Pageboy` and its working magically ✨ -Easier to implement than I thought

I'd like to know if its possible for a `Page` to transition above the next or previous like the image below. For my usecase, I have two pages. One has an ImageView background extending the bounds of the screen, the other is a tableView. A simple swipe transition is not that enchanting as it just pushes the VC out of the way. Im using infinite scroll.

Ive been playing around with interpolating the colors but its difficult since in my secondView with the background Image, the user is constantly changing their background Photo so its a masterful performance art to create smooth interpolations.

Snapchat offers a potential solution. Sliding above another Page so I can have one universal color interpolating effect instead of trying to match the varying colors of the BackgroundImage in my second Page (Hope I made sense)
![img_4585](https://cloud.githubusercontent.com/assets/2222881/24008115/10a04ae8-0a47-11e7-9328-6764276f3b9a.PNG)

**Comment by msaps** [comment]
Hi, this layout again would be possible using a combination of `Pageboy` / a parent view controller hierarchy:
```
-> ParentViewController (camera view controller)
     -> PageboyViewController
          -> LeftViewController
          -> InvisibleViewController
          -> RightViewController
```

The 'InvisibleViewController' would just be a view controller that is transparent, and allows touches through to the parent 'CameraViewController'. This would give you the 'above' transition effect akin to what Snapchat does.

To achieve the color interpolation all you would have to do is observe the values coming out of `pageboyViewController:didScrollToPosition:direction:animation` and adjust the color of a view in the parent view controller.

**Comment by otymartin** [comment]
@msaps 
I did this effortlessly and it worked beautifully.
Thank you!!

**Comment by msaps** [comment]
Glad to hear it! 👍

**Comment by otymartin** [comment]
@msaps I really hate to ask you this as it may be out of scope but I also think it would greatly help other users of this library trying to emulate that snapchat setup - it makes it super easy.

I'm finding it impossible to translate `touch-events` from the `InvisibleViewController` down to the `ParentViewController`. Care to provide some pointers?

**Comment by msaps** [comment]
Hi @otymartin no worries. I've created a new repository [Pageboy-Layouts](https://github.com/uias/Pageboy-Layouts) for this purpose. I'll try and get a Snapchat layout implemented soon and investigate the touch events issue.

**Comment by otymartin** [comment]
@msaps 
Wow that would be a major help!!
Thank you! :)
