### ISSUE TITLE
Multiple Inheritance of UIViewController Subclasses

### ISSUE THREAD

**Issue by bovillaios** [uias/Pageboy#248]
Hi Team,

Thanks for the framework.

We are creating a subclass named AppBaseVC from UIViewController, where it has App Theme etc.

We had integrated Pageboy which works fine but we are unable to Inherit AppBaseVC & PageboyViewController, as swift doesn't support multiple inheritances.

Is there any possibility to achieve this? Will this Pageboy works if we drag and drop the file into Project and change the superclass of PageboyViewController to AppBaseVC?

Thanks in advance,
Ram

**Comment by msaps** [comment]
@bovillaios as you said Swift doesn't support multiple inheritance - could you achieve your desired structure by embedding a `PageboyViewController` as a child view controller of an `AppBaseVC` view controller?
