### ISSUE TITLE
'XCP Connection interrupted' on button Tap in GradientViewController class

### ISSUE THREAD

**Issue by csprasad** [uias/Pageboy#249]
Hey Team,
I'm using your pod for the first time, and whenever I tap a button in its parent class(i.e GradientViewController) app will get stuck(screen freezes) and I only see XCP Connection Interrupted in the console, only one line shows nothing else any help will be appreciated.

**Comment by msaps** [comment]
@csprasad is this related to the Example project? `GradientViewController` isn't part of the pod sources..
