### ISSUE TITLE
Is it possible to add pages dynamically ?

### ISSUE THREAD

**Issue by AndresCianio** [uias/Pageboy#32]
I love the way this controller works, but I'm finding it difficult to make changes dynamically.  
I need to be able to add & remove pages dynamically according to actions taken by the user. Let's say I load the pager with 3 pages, and in the second one the user taps a button. Then, I would have to add a new controller at the end. And maybe at some point the user does something and I have to remove the following page. That kind of things...

The thing is, from what I see, the pager loads pages when created using the delegate, and there is no way to dynamically add a new page 'on the fly'.
Is it possible to do so somehow?

**Comment by msaps** [comment]
Hi @AndresCianio 

The way that `PageboyViewControllerDataSource` currently works doesn't make this sort of thing simple, but it is possible.. By calling `reloadPages` you can refresh the entire data source, calling `viewControllers(forPageboyViewController:)`  and `defaultPageIndex(forPageboyViewController)` again. 

In theory, you could handle this removal/addition behaviour by keeping a list of all view controllers in your `PageboyViewController` subclass and returning a subset of this list in `viewControllers(forPageboyViewController:)` according to your current state.  

I do think that this is an interesting use-case, I'll raise it as an enhancement and see if I can provide support for this in a better way.

**Comment by AndresCianio** [comment]
Hi @msaps ! Thanks a lot for the super quick answer!! I really appreciate it!
I just managed to get it working :D and I think I mostly did the same you are suggesting.

Playing around with the demo I ended up making the following changes (in case you want to try it out, or somebody ends up here at some point):

1. define a method `addPage()` in the PageVC. Virtually this method would add a new controller to an array of pages, but here I just increment `numberOfPages` by one (made it var) and then call `reloadPages()`.
2. add a button in ChildVC and a 'myDelegate' reference to the PageVC. When the button is tapped I call `myDelegate.addPage`
3. when creating each controller, set the `myDelegate` reference to `self`.
4. in `func defaultPageIndex(forPageboyViewController pageboyViewController: PageboyViewController) -> PageboyViewController.PageIndex?` instead of just returning `nil`, if the `currentIndex` is defined, I return `PageIndex.atIndex(index: currentIndex)`; otherwise keep returning `nil`.

I'd tweak the whole solution to my specifics (ie an array of pages instead of creating them), but I think this works perfectly, and love your lib!

What do you think?

**Comment by AndresCianio** [comment]
It is working as expected with the explanation above... Closing 😃
