### ISSUE TITLE
Cocoapods version outdated

### ISSUE THREAD

**Issue by AndresCianio** [uias/Pageboy#33]
It seems the cocoapods version is not the stable 1.0.0 :(
With `pod 'Pageboy'` I get the following: `Installing Pageboy (0.4.12)`

**Comment by msaps** [comment]
Hi @AndresCianio, try running `pod repo update` and then `pod install` again.

**Comment by AndresCianio** [comment]
Ups, you are 100% right. Sorry about that, thanks!
