### ISSUE TITLE
Retain cycle

### ISSUE THREAD

**Issue by shitoexe** [uias/Pageboy#34]
Hello. I have found retain cycle between PageboyViewController and PageboyAutoScroller. They keep each other in loadView method. Could you make handler property in PageboyAutoScroller as weak? Thank you.

```
open override func loadView() {
        super.loadView()
        
        self.autoScroller.handler = self
        self.setUpPageViewController()
    }
```

**Comment by msaps** [comment]
@shitoexe thanks for pointing this out! Now fixed and available in [1.0.1](https://github.com/uias/Pageboy/releases/tag/1.0.1)
