### ISSUE TITLE
Presenting on detached view controllers is discouraged

### ISSUE THREAD

**Issue by otymartin** [uias/Pageboy#41]
@msaps 
As you know I have the current view hierarchy 
```
-> ParentViewController 
     -> PageboyViewController
          -> InvisibleViewController
          -> RightViewController
```

In my right VC is a collectionView. When I click one of the cells, I segue to a modal view controller and get the warning `Presenting view controllers on detached view controllers is discouraged...UIPageViewController`

Not sure why since I added pageboy as a child controller on my parentVC. I dont have a problem present VC's from PageboyViewController itself.

**Comment by otymartin** [comment]
My temporary solutions right now is to perform my segues from `PageBoyViewController` instead of `RightViewController` which works well, unless theres a more appropriate solution, is this the way to go?

**Comment by msaps** [comment]
@otymartin just had a quick look and I think this issue was resolved in the latest release of Pageboy, [1.0.2](https://github.com/uias/Pageboy/releases/tag/1.0.2).

There was a missing child view controller function call which caused lifecycle issues. Please try updating to 1.0.2 and see if that resolves the issue? 👍

**Comment by otymartin** [comment]
@msaps  thanks this totally works after the update 🙌

**Comment by otymartin** [comment]
@msaps Hey, im having trouble making this layout work when `in-call status bar` appears. 
```-> ParentViewController 
     -> PageboyViewController
          -> InvisibleViewController
          -> RightViewController```
My childcontrollers appear to move down 40px and I get constraint error logs.

I tried to find in your code to see how you handle the `in-call statusbar` frame change but theres nothing yet everything works well in the pageboy example app.
