### ISSUE TITLE
New feature request

### ISSUE THREAD

**Issue by chamira** [uias/Pageboy#54]
Below delegate method will be called for even fraction change of the contentOffset
```
    func pageboyViewController(_ pageboyViewController: PageboyViewController,
                               willScrollToPageAtIndex index: Int,
                               direction: PageboyViewController.NavigationDirection,
                               animated: Bool)
```

But there is no corresponding stop delegate method **IF** page index does not change.

In the example code, the previous and next buttons (button bar) are updated in by implementing above method, but if contentOffset is changed fractionally page does not change (index) therefore buttons (previous/next) would not update its enabled/disabled status.

**Comment by msaps** [comment]
Hi,

When would the new delegate function be called? Currently `didScrollToPageAtIndex` isn't called when the page view controller returns to the page it departed from if a full scroll wasn't completed. 

Are you suggesting there would be an additional function that would be called in that case? Something like `didReturnToPageAtIndex...`?

**Comment by chamira** [comment]
Yes exactly! In your example project, When you are at the first or the last page if you scroll page **slightly** the next/previous button gets enabled but as the page jumps back, the button stays enabled.

**Comment by msaps** [comment]
@chamira I've just fixed the example project by updating the state of the buttons in `didScrollToPosition`. This resolves the issue of any partial scroll update.

I have had a look into doing a change to the delegate behaviour and calling `didScrollToPageAtIndex` when a page is returned to following a partial scroll, and I don't think it's that feasible for a few reasons:
- It's difficult to ensure that `didScrollToPageAtIndex` is only called once for a page index update - as currently duplicate indexes (i.e. the current page) are never reported.
- Not sure adding a further delegate method is that useful/appropriate.
- The functionality is already possible by observing values from the `didScrollToPosition` delegate method.  

Please do let me know your thoughts..

**Comment by chamira** [comment]
As long as ```didScrollToPageAtIndex``` can handle the case.. all good 👍
