### ISSUE TITLE
Are there any built transition animations?

### ISSUE THREAD

**Issue by iSaadSalman** [uias/Pageboy#57]
Hi,

Is it possible to show transition while switching the pages?

Thanks

**Comment by msaps** [comment]
@iSaadSalman currently not, other than the default scroll transitions provided by `UIPageViewController`. 

However it is something I'd definitely like to improve on and add support for! 👍

**Comment by msaps** [comment]
@iSaadSalman custom transition support is now available as of [1.1.0](https://github.com/uias/Pageboy/releases/tag/1.1.0) 😄
