### ISSUE TITLE
Is really nice how you have didScroll to and passing the offset. 

### ISSUE THREAD

**Issue by Marlon-Monroy** [uias/Pageboy#63]
It would be nice to be able to scroll by points. 
I have a control that needs to scroll a pager but both need to be in sync so It works nice when I scroll the pager but when scrolling my own menu I can't pass the scroll offset to pageboy in order to scroll it.

**Comment by msaps** [comment]
I'll see if I can get this added in the next release. 😄

**Comment by msaps** [comment]
Closing this as after investigation this is not possible due to the way that `UIPageViewControllerDataSource` functions 👎
