### ISSUE TITLE
Space has been added while call in bar active but now shown

### ISSUE THREAD

**Issue by iSaadSalman** [uias/Pageboy#64]
I have a view controller (with pageboy) which is being present modally. I'm disabling the status bar manually:
`override var prefersStatusBarHidden : Bool {
        return true
    }`

The constraints of the parent view in VC is set to 0,0,0,0 (left,right, bottom, top respectively ). Now what I noticed is when Callin Status bar is triggered, the page view is pushed and there is 20 pixel empty space from the top. 

Parent view is respecting constraints but pageboy somehow pushed.

Can you please help me with that?

Regards.

**Comment by msaps** [comment]
Hi,

I think this is related to #61 in some way, and seems to be a bug with the layout code within a `PageboyViewController` when the in-call status bar is active. I'll take a look and try and get a fix out ASAP 👍

**Comment by msaps** [comment]
@iSaadSalman this should be resolved as of [1.1.0](https://github.com/uias/Pageboy/releases/tag/1.1.0) 😄
