### ISSUE TITLE
Add support for Right-to-Left language localisation to iOS 8.

### ISSUE THREAD

**Issue by msaps** [uias/Pageboy#79]
When iOS 8 support was added, a fallback was not added for Right-to-Left localisation in iOS 8.0. See [LocalizationUtils](https://github.com/uias/Pageboy/blob/master/Sources/Pageboy/Utilities/LocalizationUtils.swift).

**Comment by farshadmb** [comment]
@msaps Because RTL UI Layout Support introduced when iOS 9 released

**Comment by msaps** [comment]
@farshadmb the `userInterfaceLayoutDirection(for:)` `UIView` function was only added in iOS 9, but `userInterfaceLayoutDirection` has been available on `UIApplication` since iOS 5.0. That was the previous recommended way for detecting a RtL layout.

**Comment by farshadmb** [comment]
@msaps Thanks your. I need to investigate that feature and how could we deal with it.

**Comment by msaps** [comment]
Now fixed as of [1.3.1](https://github.com/uias/Pageboy/releases/tag/1.3.1)
