### ISSUE TITLE
Strong And Weak Reference Issue (MemoryLeak)

### ISSUE THREAD

**Issue by farshadmb** [uias/Pageboy#83]
@msaps Hi man
Here I am again 😊 😁
I found another issue that is critical in my opinion. The "Tabman" or "Pageboy", I do not know exactly. However, you use some strong reference cause appear this issue.

For Simulate what happened to me. Please Use `NavigationController` as application `rootViewController` then push object which inherits from "Tabman" library.
After that back to `rootViewController` of `NavigationController`. The "Tabman" or "Pageboy" must be deallocated after pop `TabmanViewController` or `PageboyViewController` but never called deinit
 **Note: declare `deinit` function in "Tabman" or "Pageboy" or A class inherit from both**
`deinit{ print("\(self)")` 
print self for debug log of the memory address.

**Comment by msaps** [comment]
@farshadmb I'll have a look and see if I can pinpoint which component the memory leak is occurring in. Agree it's a pretty critical issue!

**Comment by farshadmb** [comment]
@msaps I can provide the sample project and I will send to your mail

**Comment by msaps** [comment]
@farshadmb okay cheers! Probably easier to upload as an attachment on this please. Emails are easier to lose! 😄

**Comment by farshadmb** [comment]
@msaps here we go 
I attached here 
[Download](https://drive.google.com/file/d/0B2aDAOIJ54jNMkdVOTM4WERaYm8/view?usp=sharing)

**Comment by farshadmb** [comment]
@msaps  I fixed memory like issue 😊 #84

**Comment by msaps** [comment]
@farshadmb thanks!! 👍 

Merged it in, and I'll get it in `1.3.2` 😄

**Comment by farshadmb** [comment]
@msaps your welcome dude
it seems we would be a great team 😊

**Comment by msaps** [comment]
Fixed as of [1.3.2](https://github.com/uias/Pageboy/releases/tag/1.3.2).

**Comment by msaps** [comment]
@farshadmb really appreciate all the work! 👍

**Comment by farshadmb** [comment]
@msaps now we can go to `Tabman` library and support library for iOS 8 and some bugs which I found on
