### ISSUE TITLE
Add support for initialization options

### ISSUE THREAD

**Issue by rainypixels** [uias/Pageboy#90]
Apologies if I missed this, but it seems like there's no way to supply [the third argument (`options`)](https://developer.apple.com/documentation/uikit/uipageviewcontroller/1614105-init) for a `PageboyViewController`.  This is really the only way to add space between pages via the [`UIPageViewControllerOptionInterPageSpacingKey`](https://developer.apple.com/documentation/uikit/uipageviewcontroller/options_keys) option key. 

Maybe initial support could be provided with an API similar to `navigationOrientation`?

```
public var interPageSpacing : CGFloat = 0 {
    didSet {
        guard self.pageViewController != nil else { return }
        self.setUpPageViewController(reloadViewControllers: false)
    }
}
```

This is an incredible library (thank you!) but the inability to specify space between pages is a bit of a dealbreaker right now. 😭

**Comment by msaps** [comment]
Hi, 

I'll see if I can add support for both these parameters via properties ASAP. 👍

**Comment by msaps** [comment]
@rainypixels this is now available in [1.4.0](https://github.com/uias/Pageboy/releases/tag/1.4.0) 😄

**Comment by rainypixels** [comment]
Well, that may be _the fastest turnaround for a feature request_ that I've ever experienced! 🎉 🎉 🎉 🙌🏽 🙌🏽 🙌🏽 Huge thanks, @msaps! Truly. 

(for reference, I am considering shipping pageboy in our upcoming app — digest.io)

**Comment by msaps** [comment]
@rainypixels glad to hear it, you’re welcome 😀 caught me at a good time!

Looks really cool, like the website! Feel free to raise any other issues/requests you come across when using Pageboy! 👍
