### ISSUE TITLE
[2.0 beta.2] PageboyViewController.currentViewController should not call datasource method.

### ISSUE THREAD

**Issue by muukii** [uias/Pageboy#93]
I've tried 2.0 beta.2.
Thank you for redesign data sources!
So, I can improve performance.

But, I have a question(opinion).
PageboyViewController.currentViewController will return ViewController from dataSource's method in currently.
This behavior will return the wrong instance of ViewController depends on dataSource's implementation.
I think that it should return displaying ViewController.

What do you think?

**Comment by msaps** [comment]
Hi @muukii 

You're definitely right there, I've updated this in the latest beta. Also added tvOS support! 

Please check out [Beta 3](https://github.com/uias/Pageboy/releases/tag/2.0.0.beta.3) 😄
