### ISSUE TITLE
[2.0.0 beta 3] Build failed on Carthage

### ISSUE THREAD

**Issue by muukii** [uias/Pageboy#95]
Please try it in your environment.

<img width="904" alt="screen shot 2017-07-29 at 13 25 42" src="https://user-images.githubusercontent.com/1888355/28742118-9eaa5128-7462-11e7-8068-bb5aaa1d4660.png">

**Comment by msaps** [comment]
@muukii as described in #94 the issue was with an unnecessary Xcodeproj hiding after adding the tvOS target. 

Will get it fixed in a new release.

**Comment by msaps** [comment]
@muukii for now if you build off `develop` this issue should be resolved 😄

**Comment by msaps** [comment]
Resolved in [2.0.0 Beta 4](https://github.com/uias/Pageboy/releases/tag/2.0.0.beta.4) 👍

**Comment by muukii** [comment]
@msaps Thanks!
