### ISSUE TITLE
Best place to put network code?

### ISSUE THREAD

**Issue by otymartin** [uias/Pageboy#96]
@msaps 
Hey, I'm just curious about this. I have the snapchat like layout with a ParentVC and 3 ChildControllers.
I notice though if I have network requests in `viewDidLoad` of VC's that arent my 'defaultPageIndex', scrolling to them causes a lag/freeze in my UI until the request completes.

For instance. given VC [1,2,3] where defaultPage is VC2
I have network code in my defaultPage which works fine. But when I scroll to VC1, both VC1 and VC3's viewDidLoad fires. So while VC3 is not in view, its performing network requests and updating UI which causes a lag and other times outright freeze. This despite the fact that the code is running in the background. So how can I solve this problem with this layout?

1?. Use a singleton to handle network requests and only update UI when Page comes into view?
2?. Or Only perform network requests in ParentView then update Page UI when it comes into view?

**Comment by otymartin** [comment]
I guess a simpler question is, with a similar layout, does not snapchat populate their multiple UI without (performing network requests, mapping, sorting e.t.c) while user can freely swipe between VCs free of lag and freezes?

**Comment by msaps** [comment]
@otymartin Hi 😄 

The view lifecycle behaviour is managed by `UIPageViewController`, I'm not sure the behaviour is documented for what view controllers it will initialise and `loadView` depending on the page index, but this shouldn't really be a problem.

Performing network requests also shouldn't cause an issue with Pageboy UI performance, are you sure that the requests are executing in the background? Have you tried running Instruments and seeing what is using significant amounts of time when paging between view controllers? Check out the Time Profiler 🕙

Let me know how you get on..

**Comment by farshadmb** [comment]
@otymartin Hi 
I agree with @msaps. I think you have a bunch of codes which work on the main thread. As we know apple mention that main thread is for presenting and rendering layout and UI. Don't use main thread for the logical purpose. 
Please put your sample code here to understand the issue. Also, make you solve it.
I use [AFNetworking](https://github.com/AFNetworking/AFNetworking) or [Almofire](https://github.com/Alamofire/Alamofire) for networking.

Check out this repos [Awsome iOS](https://github.com/vsouza/awesome-ios)

**Comment by otymartin** [comment]
@msaps @farshadmb 
The code that was really causing me this headache was mapping an array after a network request finished.  I managed a temporary fix (Actually it was a total accident i still dont know what fixed it)  by just moving all my network code to the `defaultPageIndex` and not updating other childControllers until they come in view. It seems to work well but will probably need to dig deeper to see why this was a problem in the first place. 

@farshadmb I stuck everything in the background and no luck🙈🙈

```swift
let sessions = results.map { Flex(partner: Person($0.object(forKey: FlexKey.partner) as! PFUser), flex: Person($0.object(forKey: FlexKey.flex) as! PFUser), session: $0) }
````

Full Disclosure. Im using IGListKit so the data mapped there eventually I would do `IGListKitAdapter.performUpdates(animated: true, completion: nil)` to show it on my childController's collectionView (Which is not in view).

**Comment by farshadmb** [comment]
@otymartin Hi 
Do you have any remote desktop application such as TeamViewer. I will join your session then I see your application performance. maybe I could fix it
