### ISSUE TITLE
Passing data between ViewControllers

### ISSUE THREAD

**Issue by Recouse** [uias/Pageboy#97]
How to pass data between pageboy `ViewController`s?

**Comment by msaps** [comment]
Hi, 

Do you mean between the child view controllers or passing something from the parent `PageboyViewController` to the child??

There is an extension on `UIViewController` which provides `parentPageboyViewController` to access the parent from a child?

**Comment by Recouse** [comment]
Hello,
I mean between the child view controllers and from parent to the child too.

**Comment by msaps** [comment]
@Recouse well you can access the parent with the above variable and cast it as required. Injecting dependencies into the child view controllers should be possible when you initialise them in the `PageboyViewController`?

**Comment by Recouse** [comment]
Now I use https://github.com/ReSwift/ReSwift
